[package]
name = "neon-style"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
textwrap = { version = "0.16.0", features = ["hyphenation"] }
